### ISSUE TITLE
Fleiss Kappa is negative

### ISSUE THREAD

**Issue by gbmarc1** [o-P-o/disagree#1]
Fleiss Kappa is usually between 0 and 1. In your implementation, a perfect agreement is 0.0 and otherwise negative.

**Comment by o-P-o** [comment]
Hi @gbmarc1 thanks for noting this. I will address asap. Apologies for the late response!

**Comment by o-P-o** [comment]
Are you saying that it is always negative? You never see a positive value?

**Comment by o-P-o** [comment]
Have solved this issue in the previous push
