### ISSUE TITLE
How is multi-labelled data supposed to be formatted?

### ISSUE THREAD

**Issue by Alex-Bujorianu** [o-P-o/disagree#10]
It is unclear if the Krippendorff’s alpha implemented by disagree is able to support multi-labelled data, and if so, in what way it should be formatted. I have tried to pass lists and sets to represent the labels, but I get an `Unhashable type` error.

**Comment by o-P-o** [comment]
Apologies, have been busy with other things lately. Addressing issues now. Could you be more specific please?

**Comment by o-P-o** [comment]
If you update the version, I have changed the implementation so that you no longer need to pass in a `labels` argument to the class. Let me know if this solves the problem and I will close the issue.

**Comment by o-P-o** [comment]
Alex have you given this a try? If it's still persisting, could you provide a code example?

**Comment by Alex-Bujorianu** [comment]
> Alex have you given this a try? If it's still persisting, could you provide a code example?

Not yet! I will take a look at the updated documentation, try again, and let you know.

**Comment by o-P-o** [comment]
Sweet thanks. I have updated the Jupyter notebooks too so it may be easier to follow the framework in there but replacing the example data with your own. Thanks.
