### ISSUE TITLE
Issue with kripp.alpha(data_type="ordinal") ?

### ISSUE THREAD

**Issue by ross-mitchell** [o-P-o/disagree#2]
Hello:

Thank you very much for developing and releasing this package! I am using your latest release, v0.2.5

I am trying to use this to calculate Krippendorff's alpha for ordinal data. However, the code in the attached notebook generates a TypeError.

I have attached a small excel file with a simple test dataset, along with a jupyter notebook that demonstrates the error.

Here is the error output:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-3ea6f01a8b92> in <module>()
----> 1 kalpha = kripp.alpha(data_type="ordinal")

~/anaconda/envs/py36/lib/python3.6/site-packages/disagree/metrics.py in alpha(self, data_type)
    477 
    478         observed_disagreement = self.disagreement(obs_or_exp="observed",
--> 479                                                   data_type=data_type)
    480         expected_disagreement = self.disagreement(obs_or_exp="expected",
    481                                                   data_type=data_type)

~/anaconda/envs/py36/lib/python3.6/site-packages/disagree/metrics.py in disagreement(self, obs_or_exp, data_type)
    448                     delta = self.delta_nominal(str(v1), str(v2))
    449                 elif data_type == "ordinal":
--> 450                     delta = self.delta_ordinal(str(v1), str(v2))
    451                 elif data_type == "interval":
    452                     delta = self.delta_interval(str(v1), str(v2))

~/anaconda/envs/py36/lib/python3.6/site-packages/disagree/metrics.py in delta_ordinal(self, v1, v2)
    419         v1, v2 = float(v1), float(v2)
    420         val = 0
--> 421         for g in range(v1, v2 + 1):
    422             element1 = self.coincidence_matrix_sum[g]
    423             element2 = (self.coincidence_matrix_sum[v1] + self.coincidence_matrix_sum[v2]) / 2

TypeError: 'float' object cannot be interpreted as an integer

[test_scores.xlsx](https://github.com/o-P-o/disagree/files/3986685/test_scores.xlsx)
[test_ordinal.ipynb.zip](https://github.com/o-P-o/disagree/files/3986686/test_ordinal.ipynb.zip)

**Comment by o-P-o** [comment]
Hi, apologies for the delayed response. Can you please update your version and try again.

This is what I get now:

    data = {"A": [0, 5, 7, 6, 7, 8, 6, 4, 6, 8, 7, 7, 8, 4, 8, 9, 6, 4, 4, 6, 6],
            "B": [0, 8, 2, 6, 7, 7, 8, 2, 7, 9, 7, 6, 6, 2, 6, 6, 6, 3, 7, 9, 7],
            "C": [0, 9, 8, 6, 9, 6, 7, 6, 8, 10, 9, 9, 9, 7, 10, 9, 9, 9, 7, 9, 9],
            "D": [6, 6, 0, 7, 8, 7, 9, 7, 7, 7, 7, 7, 9, 8, 9, 9, 8, 3, 6, 7, 8]}
    df = pd.DataFrame(data)
    labels = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    kripp = Krippendorff(df, labels)

    alpha = kripp.alpha(data_type="ordinal")
    print("Kripps alpha: {}".format(alpha))

Output:

    MacBook-Air-2:disagree Olly$ python3 metrics.py 
    Kripps alpha: -0.046168916246415614
