### ISSUE TITLE
BiDisagreements takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by annak820** [o-P-o/disagree#3]
example in notebook gives error:

bidis = BiDisagreements(df, labels)

I tried bidis = BiDisagreements(df,)
but that also gives errors:
module 'utils' has no attribute 'convert_dataframe'

**Comment by gmihaila** [comment]
Same problem here :cry:

**Comment by o-P-o** [comment]
Hi guys, apologies for the late response, haven't had much time for this over the past few months. Will take a look over the next few days.

**Comment by o-P-o** [comment]
This is fixed now - closing the issue. I have updated the library to not require a list of "labels" for input, and it no longer requires you to index the labels from 0. (I.e. you can input any labels of type str, int, float that you like.)
