### ISSUE TITLE
utils missing

### ISSUE THREAD

**Issue by felixbur** [o-P-o/disagree#8]
hi
I get the error
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-50-4c6fb59e3010> in <module>
      1 import sys
      2 import disagree
----> 3 from disagree import metrics
      4 import pandas as pd
      5 

~/.envs/researcherEnv/lib/python3.6/site-packages/disagree/metrics.py in <module>
     10 from collections import Counter
     11 from tqdm import tqdm
---> 12 from utils import convert_dataframe
     13 
     14 from scipy.stats import pearsonr, kendalltau, spearmanr

ModuleNotFoundError: No module named 'utils'

simply when trying to run your example at the imports
import disagree
from disagree import metrics

**Comment by clviegas** [comment]
You can fix this by adding these two lines to metrics.py:
import os
sys.path.append(os.path.dirname(__file__))

**Comment by shohrehhd** [comment]
Sorry, what file?

**Comment by Alex-Bujorianu** [comment]
Can the authors please fix this issue? A Python library should not require manual editing in order to work. It makes the environment a lot harder to reproduce between different engineer’s machines.

**Comment by o-P-o** [comment]
Please update your version - believe this is fixed now. Let me know.
